### ISSUE TITLE
Truck across plane

### ISSUE THREAD

**Issue by ssadler** [yomotsu/camera-controls#306] opened 2022-09-21 19:02 UTC
### Is your feature request related to a problem? Please describe.

I'm using PerspectiveCamera, I'd like to be able to keep camera position z fixed when trucking, so that the camera will truck parallel to my surface even if the camera is at an angle, since this is more intuitive for the user if the world is map-like.

### Describe the solution you'd like

Could be anything:

* New input config `ACTION.TRUCK_ACROSS_Z`
* flag on controls object
* callback on controls object
* etc

### Describe alternatives you've considered

The following code achieves the desired result but only during motion, when motion stops, the camera goes to it's position with different z:

```javascript
function setTruckAcrossPlane(controls: CameraControls) {        
                                                                
  let plane = 0                                                 
  controls.addEventListener('controlstart', () => {             
    if (controls.currentAction == CameraControls.ACTION.TRUCK) {
      plane = controls.camera.position.z;                       
    }                                                           
  })                                                            
                                                                
  controls.addEventListener('update', () => {                   
    if (plane) {                                                
      controls.camera.position.z = plane;                       
    }                                                           
  })                                                            
                                                                
  controls.addEventListener("controlend", () => {               
    plane = 0                                                   
  })                                                            
}       
```                                                        

### Additional context

Many thanks for this great lib :heart:

**Comment by promontis** [comment] 2022-09-21 19:56
The default threejs orbit controls also does this AFAIK. I was just searching for a better orbit control, and found this awesome lib! However, the truck behaviour is kind of strange for my app. This feature request is exactly what I need! And like created 1 hour before... talk about coincidence!

**Comment by yomotsu** [comment] 2022-09-23 13:33
Thanks for your suggestion.

First of all, do you really need camera-controls for your app?
camera-controls is an orbit-rotation camera control, but seems your suggestion is like disabling orbit-rotation.
What you need is tracking interaction, and orbit-rotation is not required?

Also, regarding `ACTION.TRUCK_ACROSS_Z`, Z depends on camera-up. Z is depth in Y-up world but could be vertical in Z-up world.

Could you elaborate on your situation?

**Comment by yomotsu** [comment] 2022-09-23 13:45
Have you tried `cameraControls.verticalDragToForward = true`?
see: https://yomotsu.github.io/camera-controls/examples/basic.html

**Comment by promontis** [comment] 2022-09-23 14:11
> First of all, do you really need camera-controls for your app?
camera-controls is an orbit-rotation camera control, but seems your suggestion is like disabling orbit-rotation.

You might be right. The problem is that three.js doesn't seem to be able to implement zoom to cursor for some years now. There was a PR in progress, but the owner is not responding anymore, so it was closed. Everyone is now referring to this project.

I would like the following behaviour:
- on left mouse drag (one finger swipe on mac): selection (not provided by this library)
- on right mouse drag (two finger swipe on mac): truck up/down/left/right
- on pinch or scroll: zoom in/out to cursor
- on mouse move with key (eg ctrl, alt): orbit rotation

**Comment by yomotsu** [comment] 2022-09-23 14:43
@promontis
What do you expect to "selection"?
(If you think this is not related to the subject, please open another issue)

**Comment by promontis** [comment] 2022-09-23 14:47
@yomotsu For selection I don't expect anything from this library. I mean, the control shouldn't do anything on left mouse drag. 

For selection, I'm basically cast a ray to a plane, and selecting objects within the selection rectangle. So no relationship with this library.

**Comment by yomotsu** [comment] 2022-09-23 16:48
I understand. Thanks for your reply!

**Comment by ssadler** [comment] 2022-09-23 18:42
> First of all, do you really need camera-controls for your app? camera-controls is an orbit-rotation camera control, but seems your suggestion is like disabling orbit-rotation. What you need is tracking interaction, and orbit-rotation is not required?

Like promontis, I started using Camera Controls because of zoom to cursor, which is a very important feature.

> Could you elaborate on your situation?

Sure, my application is map-like, so I'd like if the users could take a perspective (with z corresponding to the altitude of the camera) and then maintaining that perspective and altitude while moving the camera.

**Comment by yomotsu** [comment] 2022-09-24 07:57
Thanks for using😊

> z corresponding to the altitude 

So, it's a Z-up world, isn't it?

> maintaining that perspective and altitude while moving the camera.

Maybe you could use boundary option.
see: https://yomotsu.github.io/camera-controls/examples/boundary.html

**Comment by ssadler** [comment] 2022-09-24 16:35
> So, it's a Z-up world, isn't it?

I guess so :slightly_smiling_face:  thanks for your patience, im a bit of a newb at 3d programming :blush: 

> Maybe you could use boundary option. see: https://yomotsu.github.io/camera-controls/examples/boundary.html

I tried this, and it almost works... In the video below you can see it, so `z` is constrained, and `x` works naturally but `y` (mouse up and down) seems to require an additional logic, which I can see is probably not part of the objective of camera controls.

Another possible solution, which might be useful for more use cases, what if setBoundary could optionally accept a function which could modify the camera position during movement?

```javascript
type PositionCallback = (mousePos: THREE.Vector2, cameraPos: THREE.Vector3): THREE.Vector3
```

Then the user could easily implement whichever wacky use case they like :slightly_smiling_face: 

I expect I can work around in the meantime though.

https://user-images.githubusercontent.com/125019/192108251-1993fae7-1d9e-4222-9c86-856bfcdb3616.mp4

**Comment by yomotsu** [comment] 2022-09-25 12:59
if you really wish to change the mouse dragging track behavior, you can extend internal methods.
see: https://github.com/yomotsu/camera-controls/pull/205#issuecomment-901984036

**Comment by ssadler** [comment] 2022-09-30 23:16
I understand this isn't really within scope for this library so I'll try to figure something else out :-). Feel free to close, at least for me.

**Comment by yomotsu** [comment] 2022-10-03 14:07
Thank you for understanding.
Let me close this issue for now.

**Closed by yomotsu** 2022-10-03 14:07 UTC
