### ISSUE TITLE
Automatic camera transitions move twice as fast is a mouse button is down

### ISSUE THREAD

**Issue by leoncvlt** [yomotsu/camera-controls#68] opened 2020-01-14 16:14 UTC
First of all, thanks for this very useful asset!

You can see the reported behaviour in the fit example: https://yomotsu.github.io/camera-controls/examples/fit-and-padding.html

Zoom out, then press one of the buttons to fit the camera view back to the box, and try clicking the mouse buttons. The transition speed definitely zooms in when a mouse button is held.

I have an app where I select 3D object with the mouse (raycasting) and fit the camera when they are clicked, but this bug causes the motion to be kinda jerky. Any way to fix this?

**Comment by yomotsu** [comment] 2020-01-15 04:55
Thanks for your report.

I couldn't reproduce the problem.
Do you mind attaching an animation Gif or video?

**Comment by leoncvlt** [comment] 2020-01-15 10:06
Interesting! I have uploaded a video of the issue on imgur: https://imgur.com/a/9yrUGqF

The first time I didn't click the mouse button during the animation and the camera tweens at the intended speed. Then I hold my mouse button during the transition to show the camera speeding up, the third time I click intermittently. You can see when I'm holding the mouse button down as a little icon appears above the cursor in the screen recording.

I'm seeing this issue on both latest chrome (79.0.3945.117) and firefox (72.0.1) on desktop, haven't tried on mobile. Thanks!

**Comment by yomotsu** [comment] 2020-01-15 11:45
Ah, I see. [here](https://github.com/yomotsu/camera-controls/blob/master/src/CameraControls.ts#L984) is the problem.

`dampingFactor`  is changed by mouse dragging.
You can disable user input while zooming.

```
cameraControls.fitTo( object, true );
cameraControls.enabled = false;
```

However, there is no camera-move-end event to re-enable it for now.
(I should add the event)

Here is an workaround.
```
cameraControls.fitTo( object, true );
cameraControls.enabled = false;
setTimeout( () => {
  cameraControls.enabled = false;
}, 1000 );
```

**Comment by yomotsu** [comment] 2020-01-15 11:51
![5](https://user-images.githubusercontent.com/212837/72431699-ccffc800-37d8-11ea-8e24-7d78d488712e.gif)

**Comment by leoncvlt** [comment] 2020-01-15 13:26
Thanks! I had the feeling it was something going on on update. Weirdly enough, setting `controls.enabled = false` was one of the first thing I tried, but wasn't working as expected. 

I looked into it a bit more, and found it that I am calling `controls.fitTo` (and therefore disabling the controls) in response to a click event on a raycasted 3D object - since the click event propagates (does not when clicking a html button), then `endDragging` events never fires and the controls are stuck in a "mouse is held down" state when being disabled.

This actually resulted in another bug I had where re-enabling the controls afterwards would cause the camera to rotate even without clicking the mouse button, because it was still in the "stuck" state.

I managed to fix this with a workaround, by calling `controls._state = 0` when disabling the controls to force it back to an `ACTION.NONE` state. It works, not sure if you can think of a least hacky way to do this :)

**Comment by looeee** [comment] 2021-09-23 13:14
@yomotsu I guess now you can use the `rest` event?

``` js
cameraControls.fitTo( object, true );
cameraControls.enabled = false;

setTimeout( () => {
  cameraControls.enabled = true;
}, 1000 );
```

Would become

```js
cameraControls.fitTo( object, true );
cameraControls.enabled = false;

cameraControls.addEventListener('rest', () => {
    cameraControls.enabled = true;
});
```

Or even

```js
cameraControls.enabled = false;
await cameraControls.fitTo( object, true );
cameraControls.enabled = true;
```

**Comment by yomotsu** [comment] 2021-09-23 14:15
@looeee Oh yeah! That's right!
Thanks for providing the great update and it saves other situations like this.

Let me close this issue.
Although, this is still kind of workaround but could solve

**Closed by yomotsu** 2021-09-23 14:15 UTC

**Comment by leoncvlt** [comment] 2022-01-19 11:49
Another workaround in case you still want to rotate the camera around during the zoom:

```js
    const _prevDraggingDampingFactor = cameraControls.draggingDampingFactor;
    cameraControls.draggingDampingFactor = cameraControls.dampingFactor;
    await cameraControls.fitTo( object, true );
    cameraControls.draggingDampingFactor = _prevDraggingDampingFactor;
```
