### ISSUE TITLE
Switch between traditional Orbital controls and First Person

### ISSUE THREAD

**Issue by FarhadG** [yomotsu/camera-controls#332] opened 2022-12-29 09:37 UTC
### Describe the bug

As I've gone through the examples, I can either get the First Person style to work or the Orbital.

It seems like after setting the `minDistance` and `maxDistance` on the controls to a small value—which I presume is the mechanism for first person controls, I can no longer set it back to its original numbers for Orbital controls.

### To Reproduce

3. See error

### Expected behavior

Ideally, I'd like to be able to have both forms of controls based on key modifiers. Any tips?

**Comment by yomotsu** [comment] 2022-12-29 12:45
Thanks for using camera-controls.
Unfortunately, camera-controls doesn't handle that.

However, you can handle the distance in your JS code.
Save the distance somewhere in your code before switching modes, then restore the distance from the saved state when switching back from another.

**Comment by FarhadG** [comment] 2022-12-30 06:53
Thank you for the super quick response, @yomotsu! Do you have any code snippet to illustrate that point? the `minDistance` and `maxDistance` values don't change as the camera moves around so not sure what values I'd be saving to swap between the different modes. Thank you for your help, in advance!

**Comment by yomotsu** [comment] 2022-12-31 04:26
`minDistance` and `maxDistance` are just a parameters for limitation.
If you wish to change the actual distance, use `dolly()`, or `dollyTo()`, as well as other methods.

For more details, please read the documentation.
https://github.com/yomotsu/camera-controls#properties

**Comment by FarhadG** [comment] 2022-12-31 08:24
Thank you for the response, @yomotsu!

My apologies, I should be more clear. I am using those methods but with the min and max distance set to low numbers, the camera lets the user look around from a first person. It appears the only way to get this behavior is with those settings at initialization. 

Ideally, I would like to be able to switch between orbiting a position and with a modifier, let the user look around from a first person angle. 

Hope that makes sense.

**Comment by FarhadG** [comment] 2023-01-11 05:08
Hi @yomotsu! I hope you had a great new year.

I've been dabbling quite a bit with the examples and I've not been able to get this to work as expected. If you'd be kind enough to provide an example, I can create a working example and contribute back to the repo for others to use in the future as well.

A few questions:

1. When I enable First Person style controls, I can no longer use the orbital style of rotating around a model or a given point. If I toggle, it resets back to the initial position or it doesn't work as I toggle back and forth between these two different states. Is there a particular way to achieve this?

2. Is there a way to have first person controls to allow for the user to fly through the scene? That is, the ability for a user to move in the direction where they are looking versus when moving forward, always moving forward in the vector of the camera's original orientation.

If I can get some guidance here, I can put together an example that will:

- Provide a user to toggle back and forth between first person (looking around) versus orbital
- Provide the user toggle fly mode when they are in 1st person

Thank you for your time and this awesome module.

**Comment by yomotsu** [comment] 2023-01-11 05:41
Thanks for your offer. however, that would be too complex as an example, I guess (but not sure).

> no longer use the orbital style of rotating around a model or a given point.

That is actually expected behavior. First person is like 0 distance orbit.

> Is there a way to have first person controls to allow for the user to fly through the scene?

I think so. However, that is out of scope of camera-controls, and should be done in user-land.

I apologize that I think the below would not be expected answers, however, camera-controls is not a well-sponsored project nor a contract work. thus I can not work for every single user. I hope you could understand.

On the other hand, bug reports or missing feature requests are always welcome and I definitely will try to work!

**Comment by FarhadG** [comment] 2023-01-11 05:46
I totally understand, @yomotsu! I didn't know if these features were available out of the box or whether I was doing something incorrect. If these don't exist in the current API, I totally understand and respect your time.

**Comment by yomotsu** [comment] 2023-01-20 15:37
Thanks for understanding.
Let me close this issue.

Thanks again for using camera-controls😊

**Closed by yomotsu** 2023-01-20 15:38 UTC

**Comment by vegarringdal** [comment] 2023-02-10 20:22
dunno if this is any help
but to enter firstperson I call this (see code) on keydown event

To exit the firstperson view Ive told users to scroll out of it with the mousewheel 😂 
Atm its working kinda nice, just when I try and combine W and keys to move up and down it gets kinda weird.
Would have been nice with a z/y axis option to forward when you want to move forward and upwards (Z is up i my models)

```ts
async function updateCenter(offset = 0.0001) {
            const camera = getCanvasController().getActiveCamera();
            const controller = getCanvasController().getActiveControls();
            const azimuthAngle = controller.azimuthAngle;
            const polarAngle = controller.polarAngle;

            // in order to archive FPS look, set EPSILON for the distance to the center
            camera.position.set(
                camera.position.x + offset,
                camera.position.y + offset,
                camera.position.z + offset
            );

            await controller.setTarget(camera.position.x, camera.position.y, camera.position.z);
            controller.azimuthAngle = azimuthAngle;
            controller.polarAngle = polarAngle;
        }
```

Small video:
https://www.youtube.com/watch?v=flqcWDznB34

**Comment by vegarringdal** [comment] 2023-02-10 20:57
Something like this could be usefull if we need to move forward and up/down at the same time
Maybe there is a build in function that can do the same..
Tried to use moveTo to move up/down after forward, but it gets weird side effects going backwards etc (maybe I messed up, tok camera poition and added distance


```ts
forwardElevation(distance, enableTransition = false, upZ = 0, upY = 0) {
	_v3A.setFromMatrixColumn(this._camera.matrix, 0);
	_v3A.crossVectors(this._camera.up, _v3A);
	_v3A.multiplyScalar(distance);
	const to = _v3B.copy(this._targetEnd).add(_v3A);
	return this.moveTo(to.x, to.y + upY, to.z + upZ, enableTransition);
}
```

**Comment by yomotsu** [comment] 2023-02-12 07:22
@vegarringdal
Thanks for your feature request.
Would it be possible to open another issue as a new feature request?
Because this has been already closed.

I think `elevastion()` is worth adding.

**Comment by vegarringdal** [comment] 2023-02-12 20:17
@yomotsu fixed https://github.com/yomotsu/camera-controls/issues/367

**Comment by yomotsu** [comment] 2023-02-13 01:06
thanks for understanding👍
